# Generated by Django 3.1.3 on 2023-02-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_nacionalidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='nacionalidades',
            name='pais',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
