# Generated by Django 3.1.3 on 2023-02-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0003_nacionalidades_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
